services:
  ##############################################################################
  # FastAPI backend
  ##############################################################################
  - name: edge-backend
    type: web
    runtime: python
    region: oregon     # or your preferred region
    plan: free         # starter plan
    autoDeploy: true
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      uvicorn backend.app.main:app --reload --port $PORT
      workingDir: backend
    envVars:
      - key: OPENAI_API_KEY          # secret
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11
    pythonVersion: 3.11

  ##############################################################################
  # Next.js 14 frontend
  ##############################################################################
  - name: edge-frontend
    type: web
    runtime: node
    region: oregon
    plan: free
    autoDeploy: true
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      npm run start --prefix frontend
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL   # "https://edge-backend.onrender.com" after first deploy
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
